### ISSUE TITLE
Test es6features example

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/manpm#24]
Is it fetching wrong file? https://twitter.com/youyuxi/status/712468392205262849

**Comment by bahmutov** [comment]
Seems there is a problem

```
[Error: GET from https://raw.githubusercontent.com/bevacqua/es6/master/readme.markdown status undefined]
  manpm Error: GET from https://raw.githubusercontent.com/bevacqua/es6/master/readme.markdown status undefined
    at /Users/gleb/git/manpm/src/get-readme.js:19:23
    at Unzip.<anonymous> (/Users/gleb/git/manpm/node_modules/simple-get/index.js:59:7)
    at emitNone (events.js:85:20)
    at Unzip.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11) +170ms
```
